### ISSUE TITLE
Build / contrib guide?

### ISSUE THREAD

**Issue by c0dewhacker** [Bre77/hibp#7]
Hi @Bre77,

I'm wanting to write a pull request to add proxy support for this plugin, however, i'm struggling a bit to work out how you build this / or if you're using dev containers?

Seems like there's multiple package managers, and the dev container build / image doesn't work with the latest commit.

No matter which package manager yarn / pnpm / node i use to attempt to build this... i get the following.... (only a small snippet). same using the devcontainer.

```bash
ERROR in ./node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/isString.js
Module build failed (from ./node_modules/.pnpm/imports-loader@5.0.0_webpack@4.47.0_webpack-cli@3.3.12_/node_modules/imports-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/home/xxxxx/hibp/node_modules/.pnpm/imports-loader@5.0.0_webpack@4.47.0_webpack-cli@3.3.12_/node_modules/imports-loader/dist/index.js:17:24)
 @ ./node_modules/.pnpm/@splunk+react-ui@4.37.0_@react-three+fiber@8.17.7_react-dom@16.14.0_react@16.14.0__react-nati_emoemlsyw26ofedlviz3mxd3bq/node_modules/@splunk/react-ui/Button.js 73:14-40
 @ ./src/main/webapp/pages/setup/index.jsx

ERROR in ./node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/has.js
Module build failed (from ./node_modules/.pnpm/imports-loader@5.0.0_webpack@4.47.0_webpack-cli@3.3.12_/node_modules/imports-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/home/xxxxx/hibp/node_modules/.pnpm/imports-loader@5.0.0_webpack@4.47.0_webpack-cli@3.3.12_/node_modules/imports-loader/dist/index.js:17:24)
 @ ./node_modules/.pnpm/@splunk+react-ui@4.37.0_@react-three+fiber@8.17.7_react-dom@16.14.0_react@16.14.0__react-nati_emoemlsyw26ofedlviz3mxd3bq/node_modules/@splunk/react-ui/Select.js 76:14-35
 @ ./src/main/webapp/pages/setup/index.jsx
 ```

npm = 10.5.0
node = v20.12.2

Thanks in advance!

**Comment by Bre77** [comment]
Builds have been broken for some time and I have no idea how to fix it. I am spending some time again today to try fix it. I'll push what I have done so far incase you have any good ideas.

**Comment by Bre77** [comment]
Ok! Builds are now fixed. I have the dev container running and its working.

**Comment by c0dewhacker** [comment]
Thanks mate, pull request submitted
